# Generated by Django 4.2.2 on 2025-10-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, null=True, unique=True)),
                ("phone", models.CharField(max_length=50, unique=True)),
                ("gender", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
